//! Generate a Rust `impl BoundaryDomain` skeleton and an adversarial harness from
//! a validated [`Topology`]. Both are derived from the SAME grid the validator
//! checks, so the scaffold cannot disagree with the topology it came from.
//!
//! What the scaffold gives you and what it leaves: the *shape* is complete — every
//! state, input, effect and legal transition is written, and every illegal
//! transition is absent (falls to `Undefined`). What is yours to fill: the data
//! each state/input/effect carries, the meaning of `Authority` / `Context` /
//! `Error`, and the guards that turn a structurally-legal transition into a
//! `Denied` one. Those are marked `TODO`.
//!
//! Compilation against `bld-kernel` is a Stage-4 check (that is when the kernel
//! dependency arrives); here the generated text is proven *syntactically* valid.

use crate::topology::{EdgeKind, Topology};
use std::fmt::Write as _;

/// A `PascalCase` Rust identifier derived from a spec name (`start_review` →
/// `StartReview`, `PerformCommit` → `PerformCommit`).
#[must_use]
pub fn pascal(name: &str) -> String {
    let mut out = String::new();
    let mut capitalize = true;
    for ch in name.chars() {
        if ch == '_' || ch == '-' || ch == ' ' {
            capitalize = true;
        } else if capitalize {
            out.extend(ch.to_uppercase());
            capitalize = false;
        } else {
            out.push(ch);
        }
    }
    out
}

/// A `snake_case` file stem from a domain name (`approval-workflow` →
/// `approval_workflow`).
#[must_use]
pub fn snake(name: &str) -> String {
    name.chars()
        .map(|ch| match ch {
            '-' | ' ' => '_',
            other => other.to_ascii_lowercase(),
        })
        .collect()
}

fn door<'a>(topology: &'a Topology, name: &str) -> Option<&'a crate::topology::DoorTopology> {
    topology.doors.iter().find(|d| d.name == name)
}

/// Distinct effect names dispatched by the proposal door's external edges, in
/// first-seen order.
fn effects(topology: &Topology) -> Vec<String> {
    let mut seen = Vec::new();
    if let Some(proposal) = door(topology, "proposal") {
        for cell in &proposal.cells {
            if let EdgeKind::External { effect, .. } = &cell.kind {
                if !seen.contains(effect) {
                    seen.push(effect.clone());
                }
            }
        }
    }
    seen
}

/// An enum block from a list of `(variant, trailing-comment)` pairs. An empty
/// list yields an empty enum (a door the domain does not use, but the trait still
/// requires as an associated type).
fn enum_block(
    out: &mut String,
    derive: &str,
    name: &str,
    doc: &str,
    variants: &[(String, String)],
) {
    let _ = writeln!(out, "/// {doc}");
    let _ = writeln!(out, "#[derive({derive})]");
    if variants.is_empty() {
        let _ = writeln!(out, "pub enum {name} {{}}\n");
        return;
    }
    let _ = writeln!(out, "pub enum {name} {{");
    for (variant, comment) in variants {
        if comment.is_empty() {
            let _ = writeln!(out, "    {variant},");
        } else {
            let _ = writeln!(out, "    {variant}, // {comment}");
        }
    }
    let _ = writeln!(out, "}}\n");
}

/// The `impl BoundaryDomain` skeleton for a domain.
#[must_use]
pub fn domain(topology: &Topology) -> String {
    let ty = pascal(&topology.domain);
    let mut out = String::new();

    let _ = writeln!(
        out,
        "//! `impl BoundaryDomain` for `{}`, generated by `bld scaffold domain`.\n\
         //!\n\
         //! Add `bld-kernel = \"0.2\"` to your Cargo.toml. Fill each `TODO`:\n\
         //! the data each state/input/effect carries, the `Authority`/`Context`/`Error`\n\
         //! types, and the guards (return `Resolution::Denied(..)` to refuse a\n\
         //! structurally-legal transition). Every ILLEGAL transition is already absent.",
        topology.domain,
    );
    out.push('\n');
    let _ = writeln!(
        out,
        "use bld_kernel::{{\n    \
         BoundaryDomain, FactResolution, Resolution, SystemEventResolution, TransitionPlan,\n    \
         Verified,\n}};\n"
    );

    // --- the associated-type enums, from the topology ---
    let states: Vec<(String, String)> = topology
        .states
        .iter()
        .map(|s| (pascal(s), "TODO: the data this state carries".to_owned()))
        .collect();
    enum_block(
        &mut out,
        "Clone, Debug, PartialEq, Eq",
        "State",
        "The states this domain can be in. Behaviour belongs to these.",
        &states,
    );

    let proposal_inputs = door_variants(topology, "proposal");
    enum_block(
        &mut out,
        "Clone, Debug, PartialEq, Eq",
        "Proposal",
        "What someone WANTS (the proposal door). Untrusted: a proposal is data.",
        &proposal_inputs,
    );

    let effect_variants: Vec<(String, String)> = effects(topology)
        .iter()
        .map(|e| (pascal(e), String::new()))
        .collect();
    enum_block(
        &mut out,
        "Clone, Debug, PartialEq, Eq",
        "Effect",
        "The external consequences your `external` edges dispatch.",
        &effect_variants,
    );

    enum_block(
        &mut out,
        "Clone, Debug, PartialEq, Eq",
        "ProviderFact",
        "Verified external truth, in your vocabulary (the fact door).",
        &door_variants(topology, "fact"),
    );

    enum_block(
        &mut out,
        "Clone, Debug, PartialEq, Eq",
        "SystemEvent",
        "Deterministic runtime facts — retries, timeouts (the system_event door).",
        &door_variants(topology, "system_event"),
    );

    // --- the seams the spec cannot fill ---
    out.push_str(
        "// The spec describes states and transitions; these are yours to define.\n\
         /// Independently verified authority. TODO: replace this placeholder.\n\
         pub struct Authority;\n\
         /// What `resolve_proposal` reads (current requirements, ...). TODO.\n\
         pub struct Context;\n\
         /// The persisted plan a fact binds against. TODO.\n\
         pub struct FactContext;\n\
         /// Your typed refusals. Add a variant per guard that can say \"no\".\n\
         #[derive(Debug)]\n\
         pub enum Error {}\n\n\
         /// The domain. It decides meaning; it neither performs effects nor writes state.\n",
    );
    let _ = writeln!(out, "pub struct {ty};\n");

    // --- the impl ---
    let _ = writeln!(out, "impl BoundaryDomain for {ty} {{");
    for (assoc, value) in [
        ("State", "State"),
        ("Proposal", "Proposal"),
        ("Effect", "Effect"),
        ("Authority", "Authority"),
        ("Context", "Context"),
        ("ProviderFact", "ProviderFact"),
        ("SystemEvent", "SystemEvent"),
        ("FactContext", "FactContext"),
        ("Error", "Error"),
    ] {
        let _ = writeln!(out, "    type {assoc} = {value};");
    }
    out.push('\n');

    write_resolve_proposal(&mut out, topology);
    out.push('\n');
    write_resolve_fact(&mut out, topology);
    out.push('\n');
    write_resolve_system_event(&mut out, topology);

    out.push_str("}\n");
    out
}

/// The variants for a door's input enum — every input it declares, or empty if
/// the door is absent.
fn door_variants(topology: &Topology, name: &str) -> Vec<(String, String)> {
    door(topology, name).map_or_else(Vec::new, |d| {
        d.inputs
            .iter()
            .map(|input| (pascal(input), String::new()))
            .collect()
    })
}

fn write_resolve_proposal(out: &mut String, topology: &Topology) {
    out.push_str(
        "    fn resolve_proposal(\n        \
         &self,\n        \
         state: &Self::State,\n        \
         proposal: Self::Proposal,\n        \
         _authority: &Self::Authority,\n        \
         _context: &Self::Context,\n    \
         ) -> Resolution<TransitionPlan<Self::State, Self::Effect>, Self::Error> {\n        \
         match (state, proposal) {\n",
    );
    if let Some(proposal) = door(topology, "proposal") {
        for cell in &proposal.cells {
            let (from, input) = (pascal(&cell.from), pascal(&cell.input));
            match &cell.kind {
                EdgeKind::Local { to } => {
                    let _ = writeln!(
                        out,
                        "            // {} --{}--> {to}\n            \
                         (State::{from}, Proposal::{input}) => Resolution::Ready(\n                \
                         TransitionPlan::Local {{ next_state: State::{} }}, // TODO: guard\n            ),",
                        cell.from,
                        cell.input,
                        pascal(to),
                    );
                }
                EdgeKind::External { to, effect } => {
                    let _ = writeln!(
                        out,
                        "            // {} --{}--> {to} (external, dispatches {effect})\n            \
                         (State::{from}, Proposal::{input}) => Resolution::Ready(\n                \
                         TransitionPlan::ExternalEffect {{\n                    \
                         next_state: State::{},\n                    \
                         effect: Effect::{}, // TODO: guard\n                \
                         }},\n            ),",
                        cell.from,
                        cell.input,
                        pascal(to),
                        pascal(effect),
                    );
                }
                EdgeKind::Record { .. } | EdgeKind::NoEdge => {}
            }
        }
    }
    out.push_str(
        "            // Every other (state, proposal) is a transition that does not exist.\n            \
         _ => Resolution::Undefined,\n        }\n    }\n",
    );
}

fn write_resolve_fact(out: &mut String, topology: &Topology) {
    out.push_str(
        "    fn resolve_fact(\n        \
         &self,\n        \
         state: &Self::State,\n        \
         fact: Verified<Self::ProviderFact>,\n        \
         _context: &Self::FactContext,\n    \
         ) -> FactResolution<TransitionPlan<Self::State, Self::Effect>, Self::Error> {\n",
    );
    let fact_door = door(topology, "fact");
    let has_edges = fact_door.is_some_and(|d| !d.inputs.is_empty());
    if !has_edges {
        out.push_str(
            "        let _ = (state, fact);\n        \
             FactResolution::Undefined\n    }\n",
        );
        return;
    }
    out.push_str("        match (state, fact.get()) {\n");
    if let Some(fact_door) = fact_door {
        for cell in &fact_door.cells {
            if let EdgeKind::Local { to } = &cell.kind {
                let _ = writeln!(
                    out,
                    "            // {} --{}--> {to}\n            \
                     (State::{}, ProviderFact::{}) => FactResolution::Ready(\n                \
                     TransitionPlan::Local {{ next_state: State::{} }},\n            ),",
                    cell.from,
                    cell.input,
                    pascal(&cell.from),
                    pascal(&cell.input),
                    pascal(to),
                );
            }
        }
    }
    out.push_str("            _ => FactResolution::Undefined,\n        }\n    }\n");
}

fn write_resolve_system_event(out: &mut String, topology: &Topology) {
    out.push_str(
        "    fn resolve_system_event(\n        \
         &self,\n        \
         state: &Self::State,\n        \
         event: Self::SystemEvent,\n    \
         ) -> SystemEventResolution<Self::Error> {\n",
    );
    let se_door = door(topology, "system_event");
    let has_edges = se_door.is_some_and(|d| !d.inputs.is_empty());
    if !has_edges {
        out.push_str(
            "        let _ = (state, event);\n        \
             SystemEventResolution::Undefined\n    }\n",
        );
        return;
    }
    out.push_str("        match (state, event) {\n");
    if let Some(se_door) = se_door {
        for cell in &se_door.cells {
            if let EdgeKind::Record { records } = &cell.kind {
                let _ = writeln!(
                    out,
                    "            // {} + {} records `{records}` (moves no state)\n            \
                     (State::{}, SystemEvent::{}) => SystemEventResolution::Record,",
                    cell.from,
                    cell.input,
                    pascal(&cell.from),
                    pascal(&cell.input),
                );
            }
        }
    }
    out.push_str("            _ => SystemEventResolution::Undefined,\n        }\n    }\n");
}

/// The adversarial harness: every proposal the topology marks `no_edge` must be
/// `Undefined` from its state. This holds against the bare skeleton (the illegal
/// pairs fall through to `Undefined` without touching a guard), so it passes
/// before you write a single guard — the boundary's structure, witnessed.
#[must_use]
pub fn adversarial(topology: &Topology) -> String {
    let ty = pascal(&topology.domain);
    let mut out = String::new();
    out.push_str(
        "//! Adversarial harness, generated by `bld scaffold adversarial`.\n\
         //!\n\
         //! Every (state, proposal) the topology marks as absent must resolve to\n\
         //! `Undefined` — a transition that DOES NOT EXIST, not one refused at\n\
         //! runtime. This runs against the generated skeleton as-is.\n\n",
    );
    let _ = writeln!(
        out,
        "use super::*; // the generated domain module\nuse bld_kernel::BoundaryDomain;\n"
    );
    let _ = writeln!(
        out,
        "fn domain() -> {ty} {{\n    {ty}\n}}\n\n\
         // These are unit placeholders in the skeleton; replace as your types grow.\n\
         fn authority() -> Authority {{\n    Authority\n}}\n\n\
         fn context() -> Context {{\n    Context\n}}\n"
    );

    out.push_str(
        "/// Every (state, proposal) pair the topology says does NOT exist.\n\
         fn illegal_proposals() -> Vec<(State, Proposal)> {\n    vec![\n",
    );
    if let Some(proposal) = door(topology, "proposal") {
        for cell in &proposal.cells {
            if matches!(cell.kind, EdgeKind::NoEdge) {
                let _ = writeln!(
                    out,
                    "        (State::{}, Proposal::{}),",
                    pascal(&cell.from),
                    pascal(&cell.input),
                );
            }
        }
    }
    out.push_str("    ]\n}\n\n");

    out.push_str(
        "#[test]\n\
         fn no_illegal_proposal_is_defined() {\n    \
         let domain = domain();\n    \
         for (state, proposal) in illegal_proposals() {\n        \
         let outcome =\n            \
         domain.resolve_proposal(&state, proposal.clone(), &authority(), &context());\n        \
         assert!(\n            \
         outcome.is_undefined(),\n            \
         \"({state:?}, {proposal:?}) is a no_edge — it must not exist\",\n        \
         );\n    }\n}\n",
    );
    out
}

/// The probe/exporter: emits this domain's REAL topology as the same topology.json
/// shape `bld topology render` produces, so `bld topology verify <spec> topology.json`
/// proves the shipped code still matches the spec. Run against the bare skeleton it
/// reports MATCHES; it starts to drift the moment you change a resolver arm.
#[must_use]
#[allow(clippy::too_many_lines)] // a code generator: mostly one long template string
pub fn probe(topology: &Topology) -> String {
    let ty = pascal(&topology.domain);
    let has_fact = door(topology, "fact").is_some_and(|d| !d.inputs.is_empty());
    let has_event = door(topology, "system_event").is_some_and(|d| !d.inputs.is_empty());
    let mut out = String::new();

    out.push_str(
        "//! Generated by `bld scaffold probe`. Exports this domain's REAL topology as\n\
         //! topology.json (the same shape `bld topology render` emits), so\n\
         //! `bld topology verify <spec> topology.json` proves the shipped code still\n\
         //! matches the spec. Needs `serde_json`. Fill the fixture + naming TODOs so\n\
         //! every LEGAL transition resolves Ready (not Denied); against the bare\n\
         //! skeleton `export()` already matches the spec.\n\n\
         use super::*;\n\
         use bld_kernel::{BoundaryDomain, FactResolution, Resolution, SystemEventResolution, TransitionPlan, Verified};\n\
         use serde_json::json;\n\n",
    );

    let _ = writeln!(out, "fn domain() -> {ty} {{ {ty} }}");
    out.push_str(
        "// TODO: fixtures that authorize every legal transition, and a stable name\n\
         // for each value (format!(\"{:?}\") is fine until a state carries data).\n\
         fn authority() -> Authority { Authority }\n\
         fn context() -> Context { Context }\n\
         fn fact_context() -> FactContext { FactContext }\n\
         fn state_name(s: &State) -> String { format!(\"{s:?}\") }\n\
         fn proposal_name(p: &Proposal) -> String { format!(\"{p:?}\") }\n",
    );
    if has_fact {
        out.push_str("fn fact_name(f: &ProviderFact) -> String { format!(\"{f:?}\") }\n");
    }
    if has_event {
        out.push_str("fn event_name(e: &SystemEvent) -> String { format!(\"{e:?}\") }\n");
    }
    out.push('\n');

    // The enumerations, from the spec.
    write_enum_fn(&mut out, "all_states", "State", &topology.states);
    write_enum_fn(
        &mut out,
        "all_proposals",
        "Proposal",
        &door_inputs(topology, "proposal"),
    );
    if has_fact {
        write_enum_fn(
            &mut out,
            "all_facts",
            "ProviderFact",
            &door_inputs(topology, "fact"),
        );
    }
    if has_event {
        write_enum_fn(
            &mut out,
            "all_events",
            "SystemEvent",
            &door_inputs(topology, "system_event"),
        );
    }

    // export()
    out.push_str(
        "\n/// Walk every (state, input) through the REAL resolvers and emit topology.json.\n\
         pub fn export() -> serde_json::Value {\n    \
         let d = domain();\n    \
         let mut doors = Vec::new();\n\n    \
         let mut proposal = Vec::new();\n    \
         for s in all_states() {\n        \
         for p in all_proposals() {\n            \
         let base = json!({ \"from\": state_name(&s), \"input\": proposal_name(&p) });\n            \
         let cell = match d.resolve_proposal(&s, p, &authority(), &context()) {\n                \
         Resolution::Undefined => merge(base, json!({ \"edge\": \"no_edge\" })),\n                \
         Resolution::Denied(_) => merge(base, json!({ \"edge\": \"denied\" })),\n                \
         Resolution::Ready(TransitionPlan::Local { next_state }) =>\n                    \
         merge(base, json!({ \"edge\": \"local\", \"to\": state_name(&next_state) })),\n                \
         Resolution::Ready(TransitionPlan::ExternalEffect { next_state, effect }) =>\n                    \
         merge(base, json!({ \"edge\": \"external\", \"to\": state_name(&next_state), \"effect\": format!(\"{effect:?}\") })),\n            \
         };\n            \
         proposal.push(cell);\n        \
         }\n    \
         }\n    \
         doors.push(json!({ \"name\": \"proposal\", \"cells\": proposal }));\n",
    );
    if has_fact {
        out.push_str(
            "\n    let mut fact = Vec::new();\n    \
             for s in all_states() {\n        \
             for f in all_facts() {\n            \
             let base = json!({ \"from\": state_name(&s), \"input\": fact_name(&f) });\n            \
             let cell = match d.resolve_fact(&s, Verified::assert_verified(f), &fact_context()) {\n                \
             FactResolution::Undefined => merge(base, json!({ \"edge\": \"no_edge\" })),\n                \
             FactResolution::Denied(_) => merge(base, json!({ \"edge\": \"denied\" })),\n                \
             FactResolution::Ready(TransitionPlan::Local { next_state }) =>\n                    \
             merge(base, json!({ \"edge\": \"local\", \"to\": state_name(&next_state) })),\n                \
             FactResolution::Ready(TransitionPlan::ExternalEffect { next_state, effect }) =>\n                    \
             merge(base, json!({ \"edge\": \"external\", \"to\": state_name(&next_state), \"effect\": format!(\"{effect:?}\") })),\n            \
             };\n            \
             fact.push(cell);\n        \
             }\n    \
             }\n    \
             doors.push(json!({ \"name\": \"fact\", \"cells\": fact }));\n",
        );
    }
    if has_event {
        out.push_str(
            "\n    let mut system_event = Vec::new();\n    \
             for s in all_states() {\n        \
             for e in all_events() {\n            \
             let base = json!({ \"from\": state_name(&s), \"input\": event_name(&e) });\n            \
             let cell = match d.resolve_system_event(&s, e) {\n                \
             SystemEventResolution::Undefined => merge(base, json!({ \"edge\": \"no_edge\" })),\n                \
             SystemEventResolution::Denied(_) => merge(base, json!({ \"edge\": \"denied\" })),\n                \
             SystemEventResolution::Record => merge(base, json!({ \"edge\": \"record\" })),\n            \
             };\n            \
             system_event.push(cell);\n        \
             }\n    \
             }\n    \
             doors.push(json!({ \"name\": \"system_event\", \"cells\": system_event }));\n",
        );
    }
    out.push_str(
        "\n    json!({\n        \
         \"generated_by\": \"scaffold probe export()\",\n        \
         \"states\": all_states().iter().map(state_name).collect::<Vec<_>>(),\n        \
         \"doors\": doors,\n    \
         })\n}\n\n\
         fn merge(mut base: serde_json::Value, extra: serde_json::Value) -> serde_json::Value {\n    \
         if let (Some(b), Some(e)) = (base.as_object_mut(), extra.as_object()) {\n        \
         for (k, v) in e { b.insert(k.clone(), v.clone()); }\n    \
         }\n    \
         base\n}\n",
    );
    out
}

/// A `fn name() -> Vec<Ty> { vec![Ty::A, Ty::B] }` from a list of spec names.
fn write_enum_fn(out: &mut String, name: &str, ty: &str, values: &[String]) {
    let variants: Vec<String> = values
        .iter()
        .map(|v| format!("{ty}::{}", pascal(v)))
        .collect();
    let _ = writeln!(
        out,
        "fn {name}() -> Vec<{ty}> {{ vec![{}] }}",
        variants.join(", ")
    );
}

fn door_inputs(topology: &Topology, name: &str) -> Vec<String> {
    door(topology, name).map_or_else(Vec::new, |d| d.inputs.clone())
}
